import { useState, useEffect } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { TrendingUp, DollarSign, Users, ShoppingCart } from 'lucide-react';

const SalesProof = () => {
  const [currentSlide, setCurrentSlide] = useState(0);

  const salesData = [
    { 
      amount: '$16,000', 
      period: 'First Month',
      growth: '+24%',
      orders: '156',
      clients: 'Fashion Store'
    },
    { 
      amount: '$25,000', 
      period: 'Launch Week',
      growth: '+45%',
      orders: '203',
      clients: 'Beauty Brand'
    },
    { 
      amount: '$35,000', 
      period: 'Best Month',
      growth: '+67%',
      orders: '287',
      clients: 'Dropshipping Store'
    },
    { 
      amount: '$8,000', 
      period: 'Opening Month',
      growth: '+18%',
      orders: '89',
      clients: 'Local Restaurant'
    },
    { 
      amount: '$17,000', 
      period: 'Holiday Sales',
      growth: '+32%',
      orders: '142',
      clients: 'Boutique Store'
    },
  ];

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % salesData.length);
    }, 4000);

    return () => clearInterval(timer);
  }, [salesData.length]);

  return (
    <section className="py-20 bg-gradient-to-br from-background to-card/50">
      <div className="container mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-6 text-accent">
            Client Success Stories
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Real revenue generated by businesses using my eCommerce solutions
          </p>
        </div>

        <div className="max-w-5xl mx-auto">
          <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-card to-secondary/20 border border-accent/20">
            <div 
              className="flex transition-transform duration-700 ease-in-out"
              style={{ transform: `translateX(-${currentSlide * 100}%)` }}
            >
              {salesData.map((sale, index) => (
                <div key={index} className="w-full flex-shrink-0">
                  <div className="p-8 lg:p-12">
                    <div className="grid lg:grid-cols-3 gap-8 items-center">
                      {/* Main Revenue Display */}
                      <div className="lg:col-span-2">
                        <div className="mb-4">
                          <p className="text-sm text-muted-foreground uppercase tracking-wide mb-2">
                            Total Revenue • {sale.period}
                          </p>
                          <h3 className="text-5xl lg:text-6xl font-bold text-accent mb-2">
                            {sale.amount}
                          </h3>
                          <div className="flex items-center gap-2 text-sm">
                            <TrendingUp className="w-4 h-4 text-green-400" />
                            <span className="text-green-400 font-medium">{sale.growth}</span>
                            <span className="text-muted-foreground">vs previous period</span>
                          </div>
                        </div>
                        
                        {/* Stats Row */}
                        <div className="grid grid-cols-3 gap-6 mt-8">
                          <div className="text-center lg:text-left">
                            <div className="flex items-center justify-center lg:justify-start gap-2 mb-1">
                              <ShoppingCart className="w-4 h-4 text-accent" />
                              <span className="text-2xl font-bold text-foreground">{sale.orders}</span>
                            </div>
                            <p className="text-xs text-muted-foreground uppercase tracking-wide">Orders</p>
                          </div>
                          <div className="text-center lg:text-left">
                            <div className="flex items-center justify-center lg:justify-start gap-2 mb-1">
                              <Users className="w-4 h-4 text-accent" />
                              <span className="text-2xl font-bold text-foreground">
                                {Math.floor(parseInt(sale.orders) * 0.7)}
                              </span>
                            </div>
                            <p className="text-xs text-muted-foreground uppercase tracking-wide">Customers</p>
                          </div>
                          <div className="text-center lg:text-left">
                            <div className="flex items-center justify-center lg:justify-start gap-2 mb-1">
                              <DollarSign className="w-4 h-4 text-accent" />
                              <span className="text-2xl font-bold text-foreground">
                                ${Math.floor(parseInt(sale.amount.replace('$', '').replace(',', '')) / parseInt(sale.orders))}
                              </span>
                            </div>
                            <p className="text-xs text-muted-foreground uppercase tracking-wide">Avg Order</p>
                          </div>
                        </div>
                      </div>

                       {/* Dashboard Screenshot */}
                      <div className="lg:border-l lg:border-accent/20 lg:pl-8">
                        <div className="text-center lg:text-left">
                          <p className="text-sm text-muted-foreground uppercase tracking-wide mb-4">
                            Live Analytics
                          </p>
                          <img 
                            src="/lovable-uploads/5f0f596e-1893-45ed-85cb-d471e9f1f8ed.png" 
                            alt="Analytics dashboard showing growth metrics"
                            className="w-full h-auto rounded-lg shadow-lg"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Navigation Dots */}
          <div className="flex justify-center mt-8 gap-3">
            {salesData.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentSlide(index)}
                className={`w-3 h-3 rounded-full transition-all duration-300 ${
                  index === currentSlide 
                    ? 'bg-accent scale-125' 
                    : 'bg-muted hover:bg-accent/50'
                }`}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default SalesProof;